# Generated by Django 4.2.3 on 2023-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='profile picture'),
        ),
    ]
